version: "3"
    
services:
  mariadb:
    build: requirements/mariadb/
    image: mariadb
    volumes:
      - db_data:${MARIADB_VOLUME_PATH}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_VOLUME_PATH=${MARIADB_VOLUME_PATH}
    restart: always
  wordpress:
    build: requirements/wordpress/
    image: wordpress
    depends_on:
      - mariadb
    ports:
      - "8000:80"
    volumes:
      - wp_data:${WORDPRESS_VOLUME_PATH}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_ADMIN=${WORDPRESS_DB_ADMIN}
      - WORDPRESS_DB_ADMIN_PASSWORD=${WORDPRESS_DB_ADMIN_PASSWORD}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_USER_PASSWORD=${WORDPRESS_DB_USER_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_VOLUME_PATH=${WORDPRESS_VOLUME_PATH}
      - DOMAIN_URL=${DOMAIN_URL}
      - WORDPRESS_PORT=${WORDPRESS_PORT}
    restart: always
  nginx:
    build: requirements/nginx/
    image: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_data:${WORDPRESS_VOLUME_PATH}
    environment:
      - CERT_PATH=${CERT_PATH}
      - NGINX_CERT=${NGINX_CERT}
      - NGINX_CERT_KEY=${NGINX_CERT_KEY}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_VOLUME_PATH=${WORDPRESS_VOLUME_PATH}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_PORT=${WORDPRESS_PORT}
      - DOMAIN_URL=${DOMAIN_URL}
    restart: always
  redis:
    build: requirements/bonus/redis/
    image: redis
    depends_on:
      - wordpress
    volumes:
      - wp_data:${WORDPRESS_VOLUME_PATH}
    restart: always
volumes:
  db_data: 
    driver: local
    driver_opts:
      type: none
      device: ${MARIADB_VOLUME_PATH}
      o: bind
  wp_data: 
    driver: local
    driver_opts:
      type: none
      device: ${WORDPRESS_VOLUME_PATH}
      o: bind
