version: "3"
    
services:
  mariadb:
    build: requirements/mariadb/
    image: mariadb
    volumes:
      - db_data:${MARIADB_VOLUME_PATH}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_VOLUME_PATH=${MARIADB_VOLUME_PATH}
    restart: always
  wordpress:
    build: requirements/wordpress/
    image: wordpress
    depends_on:
      - mariadb
    ports:
      - "8000:80"
    volumes:
      - wp_data:${WORDPRESS_VOLUME_PATH}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_ADMIN=${WORDPRESS_DB_ADMIN}
      - WORDPRESS_DB_ADMIN_PASSWORD=${WORDPRESS_DB_ADMIN_PASSWORD}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_USER_PASSWORD=${WORDPRESS_DB_USER_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_VOLUME_PATH=${WORDPRESS_VOLUME_PATH}
      - DOMAIN_URL=${DOMAIN_URL}
      - WORDPRESS_PORT=${WORDPRESS_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    restart: always
  nginx:
    build: requirements/nginx/
    image: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_data:${WORDPRESS_VOLUME_PATH}
      - certs_data:${CERT_PATH}
    environment:
      - CERT_PATH=${CERT_PATH}
      - CERT_KEY=${CERT_KEY}
      - WORDPRESS_VOLUME_PATH=${WORDPRESS_VOLUME_PATH}
      - WORDPRESS_HOST=${WORDPRESS_HOST}
      - WORDPRESS_PORT=${WORDPRESS_PORT}
      - DOMAIN_URL=${DOMAIN_URL}
    restart: always
  redis:
    build: requirements/bonus/redis/
    image: redis
    depends_on:
      - wordpress
    ports:
      - "6379:6379"
    volumes:
      - wp_data:${WORDPRESS_VOLUME_PATH}
    restart: always
  ftp:
    build: requirements/bonus/ftp/
    image: ftp
    volumes:
      - ftp_data:/home/${FTP_USER}
      - certs_data:${CERT_PATH}
    ports:
      - "21:21"
    environment:
      - FTP_VOLUME_PATH=${FTP_VOLUME_PATH}
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
      - CERT_KEY=${CERT_KEY}
      - DOMAIN_URL=${DOMAIN_URL}
    restart: always
  adminer:
    build: requirements/bonus/adminer/
    image: adminer
    depends_on:
      - mariadb
    volumes:
      - certs_data:${CERT_PATH}
    ports:
      - "4242:4242"
    environment:
      - ADMINER_PATH=${ADMINER_PATH}
      - ADMINER_HOST=${ADMINER_HOST}
      - ADMINER_PORT=${ADMINER_PORT}
      - WORDPRESS_PORT=${WORDPRESS_PORT}
      - CERT_KEY=${CERT_KEY}
      - DOMAIN_URL=${DOMAIN_URL}
    restart: always
  website:
    build: requirements/bonus/website/
    image: website
    volumes:
      - certs_data:${CERT_PATH}
    ports:
      - "9999:9999"
    environment:
      - WEBSITE_PATH=${WEBSITE_PATH}
      - WEBSITE_HOST=${WEBSITE_HOST}
      - WEBSITE_PORT=${WEBSITE_PORT}
      - WORDPRESS_PORT=${WORDPRESS_PORT}
      - DOMAIN_URL=${DOMAIN_URL}
      - CERT_KEY=${CERT_KEY}
    restart: always
volumes:
  db_data: 
    driver: local
    driver_opts:
      type: none
      device: ${MARIADB_VOLUME_PATH}
      o: bind
  wp_data: 
    driver: local
    driver_opts:
      type: none
      device: ${WORDPRESS_VOLUME_PATH}
      o: bind
  ftp_data:
    driver: local
    driver_opts:
      type: none
      device: ${FTP_VOLUME_PATH}
      o: bind
  certs_data:
    driver: local
