version: "3"
    
services:
  mariadb:
    build: requirements/mariadb/
    volumes:
      - db_data:/home/aldubar/data/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - VOLUME_PATH=${VOLUME_PATH}
    restart: always
  wordpress:
    build: requirements/wordpress/
    depends_on:
      - mariadb
    ports:
      - "8000:80"
    volumes:
      - wp_data:/home/aldubar/data/wordpress
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_ADMIN=${WORDPRESS_DB_ADMIN}
      - WORDPRESS_DB_ADMIN_PASSWORD=${WORDPRESS_DB_ADMIN_PASSWORD}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_USER_PASSWORD=${WORDPRESS_DB_USER_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - VOLUME_PATH=${VOLUME_PATH}
    restart: always
volumes:
  db_data: {}
  wp_data: {}
