name: build
on: [push, pull_request]

jobs:
  compil_job:
    runs-on: ubuntu-latest
    name: build
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t build .github/build
    - run: docker run -v $PWD:/.github/build/ build 
